# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_code', models.CharField(max_length=128)),
                ('hashed_pass', models.CharField(max_length=128)),
                ('pass_salt', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=1000)),
                ('exp_time', models.DateTimeField(verbose_name='expiration date')),
            ],
        ),
    ]
