# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, unique=True, verbose_name='Text')),
                ('password', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=1000)),
                ('exp_time', models.DateTimeField(default=datetime.datetime(2017, 4, 23, 15, 13, 47, 510435), verbose_name='Expiration date')),
            ],
        ),
    ]
